### ISSUE TITLE
Cross-post to discuss.streamlit.io?

### ISSUE THREAD

**Issue by adamkgoldfarb** [explosion/projects#1]
Hi Team,

Long-time lurker, big fan of Spacy and Prodigy, and have been riding along with streamlit post-announcement. Was thinking this repo would be an interesting example to share with the community, but I don't want to preempt any post you were planning! Let me know if you think it'd be a good idea to share with the streamlit community or if you'd prefer I not do so. Fine either way!

Thanks for all the work you do in open source!

**Comment by ines** [comment]
Aw, thanks so much! 😃 And yes, feel free to post it. The demos in this repo are kinda basic, but I guess it could be a nice example of how you can use Streamlit to quickly add a visualizer to shared datasets.

**Comment by adamkgoldfarb** [comment]
Done! Thanks again!

https://discuss.streamlit.io/t/streamlit-and-spacy-when-worlds-collide/1174
